# Generated by Django 4.2.23 on 2025-10-04 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='categories',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hub.category'),
        ),
    ]
