# Generated by Django 4.2.23 on 2025-10-08 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_business_graphicsdesign_programmingtech_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='GraphicsDesign',
        ),
        migrations.DeleteModel(
            name='ProgrammingTech',
        ),
        migrations.DeleteModel(
            name='VideoAnimation',
        ),
    ]
