# Generated by Django 4.2.23 on 2025-10-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('freelancer', 'Freelancer')], default='customer', max_length=20),
        ),
    ]
