# Generated by Django 4.2.23 on 2025-10-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_add_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
