# Generated by Django 4.2.23 on 2025-10-09 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0010_rename_title_clientrequest_project_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientrequest',
            old_name='project_title',
            new_name='title',
        ),
        migrations.DeleteModel(
            name='Hire',
        ),
    ]
