# Generated by Django 4.2.23 on 2025-10-08 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0009_alter_userprofileinfo_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientrequest',
            old_name='title',
            new_name='project_title',
        ),
    ]
